// Pillar 3 Phase 4 (ROADMAP THE LAUNCH LINE): CI workflow scaffolding.
//
// generateCiWorkflowTemplate is PURE — a string builder with zero filesystem
// access, so its exact bytes are testable without touching disk (the "pure
// decisions pure, I/O in the shell" rule from CLAUDE.md). runCiSetup is the
// one impure edge in this module: it resolves the target path under the
// caller's repo, refuses to clobber a user's customized workflow without
// --force (a safety property, not a nicety — see spec.md §4.1), and writes
// the template.
//
// This module writes `.github/workflows/pr-hero.yml` into WHATEVER repo the
// caller points it at (via `pr-hero setup --ci` / `pr-hero ci init`). It is
// NOT the pr-hero engine's own canonical example workflow — that file, at
// the same relative path inside THIS repository, is Phase 5's job (tasks.md
// 5.2), authored by hand rather than generated by this function.

import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

export const CI_WORKFLOW_RELATIVE_PATH = path.join(
  ".github",
  "workflows",
  "pr-hero.yml",
);

export function generateCiWorkflowTemplate(): string {
  return `# Generated by \`pr-hero setup --ci\` (or \`pr-hero ci init\`).
# Customize freely — re-running setup will not overwrite this file again
# unless you pass --force.
name: pr-hero Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

# pull-requests: write lets pr-hero post inline comments and a step summary.
# contents: read is enough for actions/checkout. issues: write lets it
# resolve/reply on review threads (GitHub models PR conversations as issues).
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 is load-bearing, not cosmetic: pr-hero computes
          # the pull request's diff range and commit ancestry from full git
          # history. actions/checkout's default is a SHALLOW clone, which
          # cannot produce an accurate diff or blame — trimming this line
          # does not fail loudly, it makes reviews silently miss context.
          fetch-depth: 0

      - name: Run pr-hero
        uses: juanmaagd/pr-hero@v1
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
          # Provide ONE of the two secrets below (never leave both blank).
          # BOTH inputs are wired unconditionally: an unset secret expands to
          # the empty string, which the action treats as absent, so leaving
          # the one you do not use in place costs nothing. Deleting the line
          # for the secret you DID set is what breaks — the credential never
          # reaches the action, and it fails to authenticate silently.
          #   ANTHROPIC_API_KEY       — a standard Anthropic API key, or
          #   CLAUDE_CODE_OAUTH_TOKEN — a Claude Code OAuth token
          anthropic-api-key: \${{ secrets.ANTHROPIC_API_KEY }}
          claude-token: \${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
`;
}

export interface RunCiSetupOptions {
  cwd?: string;
  force?: boolean;
  exists?: (p: string) => boolean;
}

export type CiSetupResult =
  | { status: "created"; path: string }
  | { status: "overwritten"; path: string }
  | { status: "skipped-existing"; path: string; hint: string };

export async function runCiSetup(
  options: RunCiSetupOptions = {},
): Promise<CiSetupResult> {
  const cwd = options.cwd ?? process.cwd();
  const exists = options.exists ?? existsSync;
  const targetPath = path.join(cwd, CI_WORKFLOW_RELATIVE_PATH);
  const alreadyExisted = exists(targetPath);

  if (alreadyExisted && !options.force) {
    return {
      status: "skipped-existing",
      path: targetPath,
      hint: `${CI_WORKFLOW_RELATIVE_PATH} already exists; pass --force to overwrite it`,
    };
  }

  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, generateCiWorkflowTemplate());

  return {
    status: alreadyExisted ? "overwritten" : "created",
    path: targetPath,
  };
}
